version: "3.8"
services:
  redis:
    container_name: redis-cont
    image: redis:alpine

    environment:
      - REDIS_PASSWORD=ubuntu
      - REDIS_REPLICATION_MODE=master

    volumes:
      # Save redisearch data to your current working directory.
      - ./redis-data:/data

    command:
      # Save if 1 keys are added in every 900 seconds.
      - --save 900 1
      - --port 6380

      # Set password.
      - --requirepass ubuntu
    network_mode: host


  # redisinsight: # Redis db visualization dashboard.
  #   container_name: redis-insight
  #   image: redislabs/redisinsight
  #   ports:
  #     - 8001:8001
  #   volumes:
  #     - redisinsight:/db
  #   network_mode: host


  web: # Traveling Salesman Optimization api.
    container_name: web-cont
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - redis
    env_file:
      - .env
    network_mode: host


volumes:
  redis-data:
  redisinsight:
